# ================================= Blog settings ====================================

# Blog:
title: "ch3repatz"
description: "Another personal blog of a reverse engineer"
baseurl: ""
url: "https://ch3repatz.github.io"
author: ch3repatz

# My accounts:
email: ch3repatz@gmail.com
github: https://github.com/ch3repatz

# Feeds:
feed:
  path: atom.xml

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# ================================= Build settings ===================================

markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  syntax_highlighter: rouge

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate # Pagination

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
